name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.6.14

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Install
        run: pnpm install

      - name: Build
        run: bun run build